- .ci/azure-pipelines.yml
- .github/workflows/ci-build.yml
- README.md
- ansys/dpf/core/data_sources.py
- ansys/dpf/core/operators_helper.py
- ansys/dpf/core/plotter.py
- docker/env.sh
- docs/source/api/data_sources.rst
- docs/source/api/element.rst
- docs/source/api/elements.rst
- docs/source/api/field.rst
- docs/source/api/fieldscontainer.rst
- docs/source/api/index.rst
- docs/source/api/meshed_region.rst
- docs/source/api/model.rst
- docs/source/api/operator.rst
- docs/source/api/plotting.rst
- docs/source/api/wrapped_operators.rst
- docs/source/getting_started/index.rst
- docs/source/index.rst
- docs/source/user_guide/model.rst
- testing.md
This PR patches DPF-Core for public release in regards to documentation generation and packaging.
> Patch CI for Public Release

- ansys/dpf/core/plotter.py
- docs/source/getting_started/index.rst
Plotter issue occurs while a fields container contains several field (that are supposed to be elemental and so plottable) but for some optimization reason, some are still ElementalNodal and empty (as they are empty the process did not change their location while averaging). Then checking the location only when the field is not empty is a solution.
> Plotter issue occurs while a fields container contains several fields but that some are empty and ElementalNodal

- ansys/dpf/core/field.py
- ansys/dpf/core/meshed_region.py
- tests/test_plotter.py
This is a requirement to get the CI working following updates in PyVista module. Plotting returns None unless return_camera=True in Plotter.show().
> Remove assert isinstance(cpos, CameraPosition) for plotting tests

- ansys/dpf/core/plotter.py
- tests/test_plotter.py
Fixes #88 
Quick fix, adding recognition of "text" argument for simple custom title definition by adding text on the lower_edge using pyvista.Plotter.add_text
(NB: This is sort of a test)
> custom title for mesh.plot(field)

- docs/source/user_guide/troubleshooting.rst
Add troubleshooting section related to the model and the following error:
`[libprotobuf ERROR C:\.conan\897de8\1\protobuf\src\google\protobuf\wire_format_lite.cc:578] String field 'ansys.api.dpf.result_info.v0.ResultInfoResponse.user_name' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.`
> Documentation: add troubleshooting section related to the model

- .ci/azure-pipelines.yml
- .ci/build_doc.bat
- .ci/edit_ansys_version.py
- .ci/templates/prepare-environment-linux.yml
- .ci/templates/prepare-environment-windows.yml
- .ci/templates/run-unit-tests-linux.yml
- .ci/templates/run-unit-tests-windows.yml
- ansys/dpf/core/elements.py
- ansys/dpf/core/examples/downloads.py
- ansys/dpf/core/property_field.py
- ansys/dpf/core/results.py
- ansys/dpf/core/server.py
- examples/06-distributed-post/04-distributed-msup_expansion_steps.py
- setup.py
- tests/conftest.py
- tests/test_remoteworkflow.py
- tests/test_service.py
- tests/test_workflow.py
update azure pipeline in /.ci with 4 jobs:
- Windows:  
1. create wheel
2. testing doctest, unit test no workflow, unit test workflow
3. upload to PyPi on tag
- Linux:  
1. create wheel
2. run examples
3. unit test no workflow
- WindowsAnsys2021R2:
1. create wheel
2. manually install ansys-grpc-dpf==0.3.0
3. edit ansys version for 2021R2
4. testing unit test no workflow, unit test workflow
- DocumentationLinux:
1. create wheel
2. build doc
3. publish doc on tag
Jobs are automatically ran on Pull requests changes ONLY or on branches for "master*" and "release-*"
Changes are made so that update Ansys release version is easier
Code fixes:
- tests modified to run on windows and linux
- large double and int arrays are reduced
> update ci for release 0.4.0

- docs/source/contributing.rst
- docs/source/getting_started/install.rst
- docs/source/pydpf-core_clone_install.rst
install.rst and contributing.rst now point to a common code snippet in pydpf-core_clone_install.rst for cloning and installation commands (contributing page was outdated)
> Doc: fix Contributing - cloning commands snippet

- .github/workflows/ci.yml
Trying a quick fix for this issue by changing all links for "git clone" commands and making them use https://
> Ci/fix/issue195 build actions failing due to new GitHub policy

- ansys/dpf/core/server.py
The ImportWarning when using an incompatible version of ansys.grpc.dpf is now clearer and give a link to the Compatibility section in the docs.
The previous message stated "2022R1 Ansys unified install is available" instead of "unavailable".
Also changed the raise of InvalidPortError as the use of namespace errors conflicted with the use of variable errors in the preceding lines of code.
> Improve ImportWarning in check_ansys_grpc_dpf_version

- ansys/dpf/core/core.py
- ansys/dpf/core/misc.py
- ansys/dpf/core/server.py
- requirements_test.txt
- tests/test_launcher.py
- tests/test_launcher_remote.py
This PR integrates [PyPIM](https://pypim.docs.pyansys.com/). In an environment configured for PIM, DpfServer is now able to start a remote instance of DPF and connect to it.
The integration approach is intended to follow the current pydpf direction and does not add any gRPC specific dependency. PyPIM itself being based on gRPC, it is lazy loaded under the condition that the user is starting dpf in a pypim environment. It however changes the construction of the channel from "ip/port" to any address as supported by gRPC: https://grpc.github.io/grpc/core/md_doc_naming.html
It currently comes with a limitation that the headers are not transmitted to the instances. It means that this implementation will not work if the DPF instance is behind a gateway, or in an authenticated environment.
> PyPIM integration

- docs/source/user_guide/index.rst
This feature will only be available starting ANSYS2022R2, so hiding it for now.
> Removing link to XML doc

- ansys/dpf/core/plotter.py
- examples/05-plotting/03-labels.py
- tests/test_plotter.py
Issue #219, The code used the index from enumerating the nodes instead of using the index_to_id function when retrieving the scalar value associated with a node in Plotter.add_label().
> Fixed index issue when getting scalar field value for a node.

- ansys/dpf/core/server.py
Use ANSYS_PATH environment variable as specified in Error message. 
Update Error message.
> ANSYS_PATH environment variable for default installation 

- .github/ISSUE_TEMPLATE/bug.yml
- README.md
- docs/source/getting_started/index.rst
- docs/source/getting_started/install.rst
> Improve Compatibility documentation

- ansys/dpf/core/server.py
- tests/test_launcher.py
> Add a file.exists() check for the server executable.

- .github/ISSUE_TEMPLATE/feature.yml
- .github/workflows/ci.yml
- .github/workflows/style.yml
Adding concurrency to workflow runs so that a commit to a PR will run the associated workflows while cancelling the ones still running from the previous commit. Same for pushes to tagged branches.
Also adding back the feature issue template. Apparently having a custom bug.yml meant the organization's template for feature was not used either.
> Ci/add concurrency-add back feature template

- ansys/dpf/core/field.py
- ansys/dpf/core/meshed_region.py
- ansys/dpf/core/plotter.py
- examples/05-plotting/00-basic_plotting.py
When in a Jupyter notebook, the notebook=False argument was not working when using a plot command going through Plotter.plot_contour
> Fixes the use of notebook argument for plot commands 

- .github/workflows/ci.yml
This will add wheelhouse generation and facilitate the release process and testing for several Python versions.
For now only building and testing Windows with Python 3.8 as per previous behavior.
> Build and Test using pydpf-actions - generate wheelhouse

- .github/workflows/ci.yml
Activate the option for wheelhouse creation when running the normal CI.
Right now this creates a wheelhouse only for Windows 3.8, without plotting dependencies such as pyvista and matplotlib.
Wheelhouse tested in a local venv and working.
> Add wheelhouse generation for CI

- .github/labeler.yml
- .github/workflows/label.yml
Partially resolves #218 
Adding a label.yml workflow and a labeler.yml (used by actions/labeler) means that PRs will now get automatic labels based on the content they modify (thanks to actions/labeler) and/or the branch name.
This can be changed manually by the creator of the PR, but it is useful for classifying PRs better and more easily when drafting a Release.
> Add a PR labeler

- docs/source/conf.py
Documentation is missing [Sphinx-copybutton](https://sphinx-copybutton.readthedocs.io/). This PR simply adds it to the extensions as well as sorting them.
> add copybutton

- .github/workflows/pydpf-post.yml
The goal is to first add a manually triggered workflow for testing PyDPF-Post.
The manually triggered action offers to select the Core branch on which to run the workflow.
The PyDPF-Post branch name to test against can be given as input and defaults to "master".
This is to test the workflow and later integrate it in regular testing.
This needs to be merged in master before it can be tested.
See:
https://levelup.gitconnected.com/how-to-manually-trigger-a-github-actions-workflow-4712542f1960
> Add a manually triggered workflow for testing of pydpf-post

- .github/workflows/pydpf-post.yml
This makes the manually triggered testing workflow for PyDPF-Post work.
> The branch name given must changed to a string

- setup.py
Since the release of ansys-dpf-gate, the protos have been generated and are compatible with higher versions of protobuf.
> Remove restriction on protobuf

- .github/workflows/ci.yml
- .github/workflows/retro.yml
- tests/test_python_plugins.py
https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
> Test on ubuntu-latest as 18.04 is deprecated.

- ansys/dpf/core/support.py
Solves #473 
Fix an import error (due to the latest development of Generic Supports) when using ansys-grpc-dpf 0.3.0 with Ansys 212 and initializing a TimeFreqSupport.
> Fix Ansys R212 compatibility issue.

- ansys/dpf/core/settings.py
Always set pv.global_theme.lighting to False, without running a pyvista plotter first.
Mirroring a fix made on the TFS side.
Context:
Depending on the runner (on TFS it was the Linux one), the pyvista lighting could make opengl crash.
The fix found first and working on GitHub was to set the lighting to False when using a specific version of Mesa OpenGL.
A pyvista plotter was first run to find out what OpenGL version was installed. 
This crashed the pytest session on the Linux runner for TFS.
Setting this to False always to fix both problems and any other potential configuration, until the fix on the pyvista side is deployed.
> Mirror fix to the TFS pipeline

- requirements/requirements_docs.txt
Sphinx 5.2.0 got out this weekend and seems to break doc generation. Several issues pending on the Sphinx Github.
Edit: Sphinx 5.2.1 got out in the night of 09/25, yet our latest pipelines seem to still break.
> force sphinx to 5.1.1

- .github/workflows/ci.yml
- ansys/dpf/core/streams_container.py
- docs/source/getting_started/install.rst
- examples/03-advanced/02-volume_averaged_stress.py
- examples/06-distributed-post/02-distributed-msup_expansion.py
- requirements/requirements_docs.txt
The documentation generation job does not fail as long as "something" is in docs/build to be zipped, which is a problem when the documentation build script does not raise a failure although the generation is not complete.
Adding a step checking that index.html exists.
Could also add a criterion on the size of the folder.
> Add necessary check after documentation build

- ansys/dpf/core/animator.py
- tests/test_animator.py
Reduces test_animator.py total time from 50s to 10s by removing GIF generation at every test except one, and by reducing the number of timesteps in the FieldsContainer to animate to 2 instead of the whole 20 initially present.
> Fix animator and reduce testing time

- docs/source/getting_started/compatibility.rst
Include pygate 0.1.2 in the compatibility for R222, as well as grpc-dpf 0.5.2, by writing 0.1.* and 0.5.* as compatible versions.
> Fix the compatibility table for R222

- examples/00-basic/03-create_entities.py
- fixed element_ids, previously it was only 1 for all elements
- changed naming from id -> n_id and e_id
> Fix 03-create_entities example

- tests/test_operator.py
- tests/test_stringfield.py
- tests/test_workflow.py
This PR aims at solving some of the Codacy code quality warnings inserted when merging the code from release 0.6.0.
The goal is to solve these issues little by little along normal development so that the Codacy quality grade improves.
These won't be notified in new PRs and will only be visible as existing problems, hence this specific PR.
> Fix code quality warnings

- docs/source/user_guide/custom_operators.rst
> Typo in custom operators documentation.

- ansys/dpf/core/fields_container.py
- examples/05-plotting/06-animate_results.py
- tests/test_animator.py
Fix the animation of a multi-component field without a "deform_by" argument.
Raise an error if fields_container obtained from the evaluation of a result or operator "deform_by" argument is not of the same length as the FieldsContainer being animated.
Improve example.
> Fix FieldsContainer.animate for specific cases. 

- ansys/dpf/core/animator.py
- ansys/dpf/core/fields_container.py
- examples/05-plotting/06-animate_results.py
An error has been found in the computation of the deformation field.
> Fix deformation in fields container animate

- ansys/dpf/core/server_context.py
- tests/test_service.py
Enable usage of an environment variable to set the default ServerContextType.
> Define the default server context with ANSYS_DPF_SERVER_CONTEXT

- .github/ISSUE_TEMPLATE/bug.yml
One critical information which was not in the bug issue template is the Ansys installation version being used to run DPF.
> Ask for Ansys version in bug issue template

- .github/workflows/ci.yml
With the automatic run of the CI workflow from an external repository, this comes into conflict with usual workflow runs on master. Concurrency between these runs should be removed.
github.run_id is unique to each run, meaning if not from a PR (with pull_request.number), there will be no concurrency.
Signed-off-by: paul.profizi <paul.profizi@ansys.com>
> Remove concurrency on CI when not a PR

- .github/workflows/ci.yml
- .github/workflows/tests.yml
- requirements/requirements_dev.txt
ansys-grpc-dpf, ansys-dpf-gate and ansys-dpf-gatebin are installed as dev versions for "tests" workflow (running with DPF 2023 R2 in dev). These dev versions wheels are taken from the private dpf-standalone repo (with the server)
> CI: Pip install core dependencies dev versions from dpf-standalone

- ansys/dpf/core/server_types.py
- tests/test_launcher_remote.py
The current implementation would fallback on the current `__ansys_version__` if no specific version was requested. However, PyDPF is compatible with multiple DPF version, artificially creating incompatibility.
This PR changes this behavior so that by default, no specific version is requested.
> When starting DPF with PyPIM, don't force the usage of a specific version

- ansys/dpf/core/server_factory.py
If ansys_dpf_server_win_v2023.2.pre0 is used and this is contained in the server folder name, v202 is parsed as Ansys version and GrpcLegacyServer is the default. This prevents this behavior to have InProcessServer instead.
> DPF Server: default server config issue 

- ansys/dpf/core/_version.py
Packaging released 22.0 and 0.7.* is not considered as a valid version anymore. 
```
Traceback (most recent call last):
File "D:\a\pydpf-core\pydpf-core\.ci\..\examples\00-basic\11-server_types.py", line 44, in <module>
legacy_grpc_server = dpf.start_local_server(config=legacy_grpc_config)
File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\ansys\dpf\core\server.py", line 230, in start_local_server
server = server_type(
File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\ansys\dpf\core\server_types.py", line 993, in __init__
check_ansys_grpc_dpf_version(self, timeout)
File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\ansys\dpf\core\server_types.py", line 334, in check_ansys_grpc_dpf_version
if not …
```
> Packaging update requires a fix in server_to_ansys_grpc_dpf_version

- .github/workflows/ci.yml
input standalone_branch_suffix should have required=False for it to be possible to run the CI on the regular standalone branch.
> Enable manual run of the CI

- .github/workflows/ci.yml
- .github/workflows/ci_release.yml
- .github/workflows/docs.yml
Calls to action `errata-ai/vale-action@reviewdog` do not work if called from a workflow which was triggered manually.
> Only call doc-style (Vale) if called by a PR or a push.

- .github/workflows/ci.yml
- .github/workflows/ci_release.yml
- .github/workflows/docs-style.yml
- .github/workflows/docs.yml
- .github/workflows/examples.yml
- .github/workflows/pydpf-post.yml
- .github/workflows/test_docker.yml
- .github/workflows/tests.yml
This PR fixes errors in the CI_release workflow seen on the weekly test on master (see https://github.com/pyansys/pydpf-core/actions/runs/3923553496)
It also improves the management of "dev wheels".
Proposed changes:
- give the event type to the docs workflow, which can then give to the doc-style workflow the correct `reporter` argument for action `errata-ai/vale-action@reviewdog` --> Vale doc style checking now works in all cases (run from CI, run manually...)
- add the `custom-wheels` argument to most reusable workflows, so we can define for each pipeline where the development wheels for `ansys-dpf-gate`, `ansys-dpf-gatebin` and `ansys-grpc-dpf` should be taken. Update `ci.yml` with this. --> Can also be given as a custom input to test wheels with manual runs.
- fix the `ci_release.yml` …
> Fix release pipeline, Vale style checking, and dev wheels management

- tests/test_operator.py
The mapdl::rst::MeshProvider will have a specification on next server version -> changing used Operator
> Fix operator specification unit test for next server version

- examples/05-plotting/03-labels.py
- src/ansys/dpf/core/plotter.py
- tests/test_plotter.py
Solves #767 
DpfPlotter.add_node_labels now correctly draws the bare meshed_region given in input, with labels, in the case where no Field was added to the plotter first.
Improved typehinting and docstrings
DpfPlotter.show_figure now warns the user that the `notebook` kwarg is to be given at initialization of the DpfPlotter.
> Fix and improve plotter.DpfPlotter behavior

- .github/workflows/update_operators.yml
Name of the created branch now includes triggering branch name to avoid conflicts.
> Improve automatic operator update pipeline

- pyproject.toml
When moving from ``pyproject.toml`` to ``setup.py``, PyDPF-Core stopped supporting Python 3.11+ versions. In your previous ``setup.py`` file, your Python limitations were ``>=3.7, <4`` and now they are ``>=3.7, <3.11``. This will cause a conflict with the PyAnsys metapackage as we can tell from: https://github.com/pyansys/pyansys-dev/issues/4
I submit this PR to replicate the previous behavior you had. I understand that this change was unintended. Consider adding a Python 3.11 smoke test in your workflow as well =)
> Allow for Python <4 versions

- .ci/build_doc.bat
- .github/workflows/docs.yml
- examples/08-averaging/01-average_across_bodies.py
The API documentation was no longer generated due to the `build_doc.bat` script not having been updated with the move of the sources into `src/`.
PS: the doc generation step now takes 31mn to complete...
> Update build_doc.bat due to the move into src/

- src/ansys/dpf/core/unit_system.py
- tests/conftest.py
- tests/test_lsdyna.py
- tests/test_unit_systems.py
Unit system functionality tests was filtered as 6.0 but should be 6.1.
> Fix minimum version required for Unit Systems

- pyproject.toml
Add an explicit dependency on `setuptools`. This is needed because the 
`pkg_resources` module is used, which is provided by `setuptools`.
Closes #784.
> Add explicit dependency on 'setuptools'

- .ci/run_examples.py
- docs/source/conf.py
- examples/08-averaging/01-average_across_bodies.py
- src/ansys/dpf/core/examples/examples.py
- tests/test_examples.py
Managing the minimal DPF version required to run an example is necessary to be able to continue CI/CD with continuous integration of examples and features only available on the DPF server currently under development, but not yet in the one already out.
For now, this is specified with a note in the header of the example, stating for example:
```
.. note::
This example requires DPF 6.1 or above.
For more information, see :ref:`ref_compatibility`.
```
The two digits version number is used, however I think we could use the DPF Server package version if we wanted to.
See [docs](https://github.com/pyansys/pydpf-core/actions/runs/4105649624) job as well as [examples](https://github.com/pyansys/pydpf-core/actions/runs/4105653287) job for the 2023.2.pre0 server.
> Add minimum DPF version logic to examples

- docs/source/getting_started/install.rst
Fix and improve the section concerning installation without an internet connection.
Also improve the regular install section by mentioning the `[plotting]` option.
> Fix and improve install section

- conftest.py
- src/ansys/dpf/core/unit_system.py
Features added to PyDPF-Core only available with the DPF server currently under development should not prevent the CI_release from running and PyDPF-Core from being able to be released anytime.
Those are marked as requiring DPF server version > XXX.
Tests are versions, examples now also deal with that, yet the docstrings examples (run through doctest) were not managed.
This PR adds a [custom doctest runner](https://docs.python.org/3/library/doctest.html#advanced-api) to detect docstring examples failing due `DpfVersionNotSupported`, and mark them as passing.
Before: https://github.com/pyansys/pydpf-core/actions/runs/4156462538/jobs/7190270043#step:8:89
After: https://github.com/pyansys/pydpf-core/actions/runs/4175995794
> Allow doctest to deal with features requiring future server version

- src/ansys/dpf/core/operator_specification.py
Following the last update of the DPF standalone, corrections to operator specifications have been made and should be propagated to PyDPF-Core.
https://github.com/pyansys/pydpf-core/actions/runs/4234502019/jobs/7356880967 tests run on the _test standalone branch.
> Update doctest for Specification.description following server-side corrections

- src/ansys/dpf/core/geometry.py
Translate coordinates to numpy array of type np.number in Line.init when not a DPF Field.
Fixes an error here https://github.com/pyansys/pydpf-core/actions/runs/4252250685/jobs/7395598740#step:11:2539
specific to Python 3.7 which still uses Numpy 1.21.6 (latest for 3.7).
> Fix Line.__init__ for Python 3.7 with numpy 1.21.6

- tests/test_lsdyna.py
Remove part_hourglass_energy from lsdyna test (the matsum branch of the binout file in the test does not contain part hourglass energy)
> Remove part_hourglass_energy from test (file does not contain it)

- src/ansys/dpf/core/operators/build.py
The related problem having been fixed, we can remove this skip during Python operators generation.
> Remove skipping cgns::pressure

- .github/workflows/ci_release.yml
`ansys-dpd-server-2023-2-pre1` is now publicly available.
> Switch standalone suffix to .pre1 in release CI

- pyproject.toml
- requirements/requirements_install.txt
Soves #931 
TLDR; `imageio==2.28.1` was released on May 3rd and is breaking our pipelines due to a deprecated keyword. Probably is an issue due to us restricting to `pyvista==0.36.1` in our pipelines due to issues with #930, since we do not call `imageio` anywhere directly.
https://github.com/pyansys/pydpf-core/actions/runs/4873975133/jobs/8694305801#step:8:309
> Fix imageio==2.28.0

- .github/workflows/ci.yml
- .github/workflows/ci_release.yml
- .github/workflows/docs.yml
- .github/workflows/examples.yml
- .github/workflows/examples_docker.yml
- .github/workflows/gate.yml
- .github/workflows/pydpf-post.yml
- .github/workflows/test_docker.yml
- .github/workflows/tests.yml
- .github/workflows/update_operators.yml
Bumps version of actions when deprecated warning was raised
Corrects paths to coverage files not found
> Remove pipelines warnings

- src/ansys/dpf/core/core.py
Temporary fix to allow development.
> Remove problematic docstring example for core.download_file

- .github/workflows/ci_release.yml
No version of `ansys-dpf-server-2024.1` being publicly available yet, the `ci_release.yml` should actually still target `ansys-dpf-server-2023.2.pre1`. Weekly runs otherwise fail.
> Revert switch to 241 in ci_release.yml

- src/ansys/dpf/core/available_result.py
- src/ansys/dpf/core/result_info.py
- tests/conftest.py
- tests/test_resultinfo.py
While working on fluid results, make improvements to the string representation of `AvailableResult`.
Requires https://github.com/ansys/pydpf-post/pull/414
> Update ResultInfo and AvailableResult print

- src/ansys/dpf/core/available_result.py
- tests/test_resultinfo.py
This allows to have a nicer list of AvailableResult objects when requesting `model.metadata.result_info.available_results`:
`[AvailableResult<name=enthalpy>, AvailableResult<name=mass_flow_rate>, AvailableResult<name=static_pressure>, AvailableResult<name=mean_static_pressure>, AvailableResult<name=rms_static_pressure>]`
> Improve AvailableResult.__repr__()

- src/ansys/dpf/core/elements.py
Fixed docstrings for Element.type as what is returned is actually an Enum ID.
> Clean-up Element.__str__

- docs/source/conf.py
- requirements/requirements_docs.txt
- requirements/requirements_test.txt
- src/ansys/dpf/core/settings.py
Hotfix for PyVista 0.41.0 released this morning.
This apparently removed the deprecated `pv.rcParams` we were still using and is breaking all our pipeline runs.
Still having an issue (which I never managed to reproduce locally neither on Windows not on Linux) with doc generation on GitHub though, requiring `pyvista==0.36.1`:
> Fix issues with PyVista 0.41.0

- .github/workflows/ci_release.yml
Setting pydpf-post checks with the latest published pydpf-post as requirements for release creates a loop preventing us from releasing pydpf-core.
We still test whether a pydpf-post release will be necessary, but it does not prevent from releasing ansys-dpf-core.
> PyDPF-Core tests on release are not requirements

- pyproject.toml
- requirements/requirements_test.txt
The lastest failures in the CI have been attributed to `ansys-api-plaftorm-instancemanagement==1.0.0b4` because it removed the pin on `protobuf<4`.
Also, `ansys-platform-instancemanagement==1.0.2` was pinned in `requirements_test.txt` but not to the latest.
This PR updates to `ansys-platform-instancemanagement==1.1.1` and tests if forcing `ansys-api-plaftorm-instancemanagement==1.0.0b3` temporarily solves our issues.
When using all latest pypim libraries and forcing `protobuf<4`: [it passes ](https://github.com/ansys/pydpf-core/actions/runs/5795021862/job/15705936037#step:15:85)
> Restrict protobof<4

- README.md
- docs/source/index.rst
Per Landon’s request in the PyAnsys Global AFT on 7/26/23, add links to the PyDPF-Core cheat sheet from this library's documentation.
Note: This library doesn't reuse the README content in the overall index.rst file for documentation. Consequently, I revised the "Documentation and issues" sections in both the README and the overall index.rst file.
> Add links for doc and cheat sheet

- .github/workflows/ci.yml
- .github/workflows/ci_release.yml
- .github/workflows/docs.yml
- .github/workflows/releaser.yml
Changes validated via a mock-up repo
> Fix doc release deployment

- README.md
- docs/source/index.rst
@PProfizi and @anslpa  There were some format errors and broken links on the README and overall index pages. I cleaned both pages up. I will also soon be adding cheat sheet links for PyPDF-Post and cleaning up these same two files in that repo.
> Fix some bad formatting and links

- docs/source/getting_started/compatibility.rst
Ansys 2023R2 was missing and library minimal versions required for Ansys 2024R1.pre1 must be the patched ".1" versions as the initial ones were yanked.
> Update compatibility for 2023R2 and 2024R1.pre1

- src/ansys/dpf/core/data_sources.py
- tests/test_datasources.py
> Revert "Fix bug 843531 - DPF: Access violation when DataSource is incorrectly constructed"

- .github/dependabot.yml
Dependabot alerts were not triggering since August 11th due to 5 PRs in progress.
Bumped the number to 10 so we can see more.
This for example prevented us from updating `ansys-sphinx-theme`, which would have prevented an issue #1144.
> Allow 10 PRs for dependabot pip updates

- examples/05-file-IO/02-hdf5_serialize_and_read.py
> Mark example "HDF5 export and import operations" as requiring DPF 7.0

- .github/workflows/docs-style.yml
- docs/.vale.ini
- docs/source/user_guide/operators.rst
Stops Vale from complaining and failing, which it has been doing for a few days, most likely due to an update somewhere.
> Vale check modified only and ignore roles

- docs/source/operator_reference_load.rst
The current parameters for the embedding of the static doc prevents from scrolling to the actual bottom of the doc.
I tested these parameters from within Chrome and they look good.
> Fix static operators documentation embedding

- .github/workflows/docs-style.yml
Limiting to `added` is not working when the CI runs on a merge commit on master when the diff is empty on files targeted by Vale.
> Revert Vale filter to nofilter

- tests/conftest.py
- tests/test_resultinfo.py
The update of `test_resultinfo.py` made following an update in the result file reference did not filter for DPF 7.1 but for DPF 7.0, which is wrong.
Before:
https://github.com/ansys/pydpf-core/actions/runs/6496374240/job/17643178410#logs
After:
https://github.com/ansys/pydpf-core/actions/runs/6496892196
> Make test_resultinfo.py retrocompatible with DPF 7.0

- examples/12-fluids/03-fluids_isosurface.py
> Revert "Update the iso_contours example using iso_surfaces operator"

- src/ansys/dpf/core/_version.py
- src/ansys/dpf/core/server_types.py
- tests/test_checkversion.py
- tests/test_server.py
This PR proposes a refactor of `ansys.dpf.core._version.py`'s `server_to_ansys_version` to enable handling `XXXX.Y.Z` DPF versioning while retaining retro-compatibility.
It also removes `server_to_ansys_grpc_dpf_version` as `ansys.grpc.dpf` is now shipped within `ansys-dpf-core`.
Instead, what is checked when connecting to a server via gRPC is whether the DPF server we try to connect to has a version at least equal to the `min_server_version` variable, which is the minimal DPF version supported by the current `ansys-dpf-core` package.
> Refactor version handling

- tests/test_propertyfield.py
Update a test that specifically checks the values of a `PropertyField` returned by the skin operator, that needs update:
- This PR comments the conflicted part.
- Then the PR in TFS will be completed.
- Then dpf_standalone will be updated.
- Then the commented part will be uncommented.
> Update tests to handle issue with skin mesh

- src/ansys/dpf/core/__init__.py
Use __name__ argument to get the correct USER_DATA_PATH when in PyInstaller.
Closes #1216
> Fix path management for PyInstaller

- README.md
- docs/source/getting_started/compatibility.rst
- docs/source/getting_started/dependencies.rst
- docs/source/getting_started/install.rst
- docs/source/user_guide/troubleshooting.rst
- docs/styles/Vocab/ANSYS/accept.txt
TLDR; `ansys-dpf-gate`, `ansys-dpf-gatebin`, and `ansys-grpc-dpf` no longer exist as separate packages. They are now directly shipped within `ansys-dpf-core` as modules. This PR changes the doc (mainly the compatibility table) accordingly.
Closes #1214
> Update compatibility and dependencies for 0.10.0

- .github/workflows/ci.yml
and not just when running the CI on master
Noticed that behavior when running a regular CI on master during a server update.
> Only update the dev doc when pushing onto master

- .github/workflows/ci_release.yml
- .github/workflows/releaser.yml
- .github/workflows/tests.yml
as it can be manually called from another branch
> Remove criterion on v tag on branch calling the releaser.yml

- src/ansys/dpf/core/available_result.py
- tests/test_resultinfo.py
Units were written in lower case for available results. This is not correct and it is also incoherent with the rest of their uses (ResultInfo and Fields, for example)
> Fix units case in available result

- src/ansys/dpf/core/data_sources.py
- tests/test_datasources.py
Quick proposal to enable working with `d3plot` files in PyDPF-Post. See ansys/pydpf-post#534.
I think this should eventually be implemented directly in the DPF `CDataSources`.
> Make DataSources recognize a d3plot file without a key

- README.md
- docs/source/index.rst
- docs/source/user_guide/custom_operators_deps.rst
Just a small mistake I found in the docs, used [rg](https://github.com/BurntSushi/ripgrep) and [rsr](https://github.com/awoimbee/rsr) to try to fix every misspelling.
BTW in this PR I'm just fixing the project name, but [typos](https://github.com/crate-ci/typos) finds a lot of mistakes, it might be a good idea to add it to your CI.
> maint(typos): rename PDF to DPF

- .github/workflows/ci.yml
- .github/workflows/ci_release.yml
- .github/workflows/docs.yml
- .github/workflows/examples.yml
- .github/workflows/examples_docker.yml
- .github/workflows/pydpf-post.yml
- .github/workflows/test_docker.yml
- .github/workflows/tests.yml
- .github/workflows/update_operators.yml
> Switch default ANSYS version to 242

- src/ansys/dpf/core/misc.py
Closes #1264 
Handle case where user put the path for `ANSYS_DPF_PATH` between quotes.
> Remove quotes from ANSYS_DPF_PATH env var

- src/ansys/dpf/core/data_sources.py
- tests/test_datasources.py
Part of work for ansys/pydpf-post#534.
Improves previous PR for automatic result key for known files without extensions (d3plot and binout)
> Detect binout files automatically

- examples/06-plotting/00-basic_plotting.py
- src/ansys/dpf/core/meshed_region.py
- src/ansys/dpf/core/meshes_container.py
- src/ansys/dpf/core/model.py
Also make it so we do not raise an automatic warning on show_figure() when called from a plot method.
> Update basic plotting example

- src/ansys/dpf/core/workflow.py
The previous docstring was wrong. Using this opportunity to clarify the behavior and add an example in the docstring.
> Improve Workflow.connect_with docstring

- .github/workflows/ci.yml
Add standalone_suffix pick job in CI for cases where PR is run by a server-sync action.
> Improve server branch selection

- .github/workflows/test_docker.yml
- doc/source/conf.py
- tests/test_server.py
Commenting-out `entry` tests on Docker, and `11-server_types.py` example when generating the doc examples gallery.
Issues to be identified later. 
See: 
- `entry` on Docker: [crash](https://github.com/ansys/pydpf-core/actions/runs/7222676515/job/19688595265?pr=1331#step:25:26), [failure](https://github.com/ansys/pydpf-core/actions/runs/7540074150/job/20523909509?pr=1353#step:25:166), [timeout](https://github.com/ansys/pydpf-core/actions/runs/7539247154/job/20521382199?pr=1352#step:25:37)
- `server_types` example on doc build: [crash](https://github.com/ansys/pydpf-core/actions/runs/7540074150/job/20523909206?pr=1353#step:18:33)
> Remove unstable tests and examples

- .ci/run_examples.py
Example 06-distributed-stress-averaging currently causes the CI to be very unstable. To be investigated.
See for example https://github.com/ansys/pydpf-core/actions/runs/7557818159
> Skip unstable example in CI

- src/ansys/dpf/core/fields_container.py
- tests/test_fieldscontainer.py
This PR adds a `FieldsContainer.plot` method.
> FieldsContainer.plot

- src/ansys/dpf/core/generic_data_container.py
- src/ansys/dpf/core/mesh_info.py
- src/ansys/dpf/core/string_field.py
- tests/test_mesh_info.py
Adds `MeshInfo.parts` helper -> returns a dictionary of part ID to part name to prevent from having to manipulate PropertyFields.
> MeshInfo.parts helper

- src/ansys/dpf/core/custom_operator.py
Based on the current venv.
Store the original `dpf-site.zip` and give a `restore` option.
> Allow update of dpf-site.zip

- src/ansys/dpf/core/result_info.py
- tests/test_resultinfo.py
Allow creation of a ResultInfo. Only available for InProcess for now.
> Create a ResultInfo

- src/ansys/dpf/core/core.py
- tests/conftest.py
- tests/test_field.py
- tests/test_meshregion.py
- tests/test_operator.py
Add test on MeshedRegion.deep_copy() with bigger mesh (failed in examples) and add fix
> Fix retro for deep_copy

- tests/entry/test_entry.py
Following license changes in DPF Server, this test was failing
Basically the behavior should not be modified apart from the Operator Construction also throwing a DPF LA Exception.
However the test seemed to run an InProcessServer before even actually running the line which starts a server.
Which caused all plugins to be already loaded, and DPF to be already loaded, and I believe biasing the expected environnement of the test.
This should be merged in synchronization with the Licensing modifications server side
> Fix test_entry.py::test_license_agr

- src/ansys/dpf/core/fields_factory.py
Arguments n_lines and n_columns were reversed
> Fix fields_factory.create_matrix_field

- .github/workflows/docs.yml
Continuation of #1302, fixes #1327 by adding the variable at step level. Everything is properly configured in the `conf.py` file and I can see the Meilisearch indices for PyDPF working as expected.
The latest stable documentation does not contain any reference to Meilisearch in its HTML, meaning that the `MEILISEARCH_PUBLIC_API_KEY` was not available when the docs built. I suspect that the `cmd` is starting a new shell with a new env, loosing track of the environment declared in the `docs.yml`.
> fix: ensure that Meilisearch secret is used in workflows

- src/ansys/dpf/core/server_types.py
Set `self.live=False` before starting initialization of a grpc server.
> Fix GrpcServer deletion after initialization failure

- src/ansys/dpf/core/__init__.py
Raises `ImportError` if `ansys-dpf-gate`, `ansys-dpf-gatebin` or `ansys-grpc-dpf` is detected as installed in the current Python environment.
> Add ImportError if any old dpf dependency is installed

- src/ansys/dpf/core/_version.py
Required for `ansys-dpf-core 0.11.0` to handle dev versions of DPF 8.1.
> Add support for DPF 8.1

- .github/workflows/ci_release.yml
- src/ansys/dpf/core/server_factory.py
Test release pipeline: https://github.com/ansys/pydpf-core/actions/runs/7900013659
Latest: https://github.com/ansys/pydpf-core/actions/runs/7914266994
> Switch CI_release.yml to 2024.2.pre0

- src/ansys/dpf/core/meshes_container.py
- src/ansys/dpf/core/scopings_container.py
The custom `__str__` methods for `ScopingsContainers` and `MeshesContainers` are not needed, as the default `Collection` method is much richer (it directly relies on sever calls). See difference:
Custom method (to be removed with this PR):
Default method:
> Remove custom __str__ methods for ScopingsContainer and MeshesContainers

- src/ansys/dpf/core/server_factory.py
See https://github.com/ansys/pydpf-core/actions/runs/7904444681
These failures are random but fail 99% of the time. Only for these doctests, only on `Ubuntu`, only for `Python 3.10` and only for the `2024.2.pre0` standalone.
Will be investigated in a further bug issue but does not prevent from releasing.
> Skip doctests in server_factory.py

- tests/test_field.py
https://github.com/ansys/pydpf-core/actions/runs/7977082146/job/21779367169?pr=1423#step:21:1224
and many other
To be investigated further
> Skip test_deep_copy_2_field for retro due to instabilities

- .github/workflows/ansys_lab.yml
- .github/workflows/ci.yml
- .github/workflows/ci_release.yml
- .github/workflows/docs.yml
- .github/workflows/examples.yml
- .github/workflows/examples_docker.yml
- .github/workflows/pydpf-post.yml
- .github/workflows/releaser.yml
- .github/workflows/test_docker.yml
- .github/workflows/tests.yml
- .github/workflows/update_operators.yml
Update several actions to remove deprecation warning for `Node.js 16`.
Update ansys_lab.yml to not fail if no diff is found.
Fix `version` argument for the `fetch-gh-release-asset` action.
Add timeouts to the PyDPF-Post tests (it sometimes hangs).
Successful run: https://github.com/ansys/pydpf-core/actions/runs/7989894623
> Several fixes to the release pipeline following 0.11.0

- doc/source/getting_started/index.rst
- doc/source/getting_started/licensing.rst
Recent PR files comparisons kept warning of Vale errors (such as [here](https://github.com/ansys/pydpf-core/pull/1465/files)).
> Fix doc styling errors reported by Vale

- src/ansys/dpf/core/_version.py
Add `"8.2"` version to be able to merge the bump to 2024.2.pre1 in the server
> Add 8.2 to prepare for post-release

- src/ansys/dpf/core/faces.py
- tests/test_faces.py
A bug was reported server side pointing to a crash if faces are requested in a mesh that doesn't have them:
```
from ansys.dpf import core as dpf
from ansys.dpf.core import examples
filename = examples.download_pontoon()
model = dpf.Model(filename)
mesh = model.metadata.meshed_region
mesh.faces.face_by_id(1) # server crashes since there are no faces
```
We now handle the situation here. A test is added to ensure that the raise is expected.
> Fix issue in model without faces

- .github/ISSUE_TEMPLATE/bug.yml
- .github/workflows/ci_release.yml
See https://github.com/ansys/pydpf-core/actions/runs/8631544966 -> passes
> Prepare release CI to 2024.2.pre1

- src/ansys/dpf/core/server_types.py
- tests/test_server.py
BUG: calling shutdown on a server prevents from starting another server on linux.
-> when a server is started, to choose the port to start the server on, all server instances are requested their ports but shutdown prevents the server to return its port. FIX is to store the port of the server before shutdown
> Fix server shutdown

- src/ansys/dpf/core/outputs.py
- src/ansys/dpf/core/results.py
I have stumbled upon operators where the output pin 0, despite being of type `fields_container`, is not named `fields_container`. 
That is an implicit rule we generally follow, not a hard one we can expect everyone to follow.
The `eval()` method should thus be made more generic.
It still tests for a `fields_container` type output pin, but it does not put any requirement on the naming.
> Fix Operator.eval() in case output pin 0 is not named "fields_container"

- .github/workflows/tests.yml
This reverts commit 85dcfedc887a651e169f7a7ce0e0b8c4fbc0bc51.
It turns out it was indeed an issue at Microsoft, which got solved within the day.
> Revert "Fix apt get ubuntu (#1533)"

- examples/06-plotting/00-basic_plotting.py
- src/ansys/dpf/core/plotter.py
> Enable parallel_projection as a kwarg

- src/ansys/dpf/core/server_factory.py
- src/ansys/dpf/core/server_types.py
- tests/test_server.py
> Fix environment PATH pollution by CGrpc servers

- src/ansys/dpf/core/data_sources.py
- tests/test_datasources.py
To better handle CFX and Fluent files with `.cas.cff`/`.dat.cff` or `.cas.h5`/`.dat.h5` extensions.
> DataSources.set_result_file_path recognizes .cas/dat.cff and .cas/dat.h5 files automatically

- src/ansys/dpf/core/any.py
- src/ansys/dpf/core/collection.py
- src/ansys/dpf/core/collection_base.py
- src/ansys/dpf/core/config.py
- src/ansys/dpf/core/custom_type_field.py
- src/ansys/dpf/core/cyclic_support.py
- src/ansys/dpf/core/data_sources.py
- src/ansys/dpf/core/data_tree.py
- src/ansys/dpf/core/dpf_operator.py
- src/ansys/dpf/core/field_definition.py
- src/ansys/dpf/core/generic_data_container.py
- src/ansys/dpf/core/label_space.py
- src/ansys/dpf/core/meshed_region.py
- src/ansys/dpf/core/operator_specification.py
- src/ansys/dpf/core/result_info.py
- src/ansys/dpf/core/scoping.py
- src/ansys/dpf/core/streams_container.py
- src/ansys/dpf/core/string_field.py
- src/ansys/dpf/core/support.py
- src/ansys/dpf/core/workflow.py
- tests/test_scoping.py
Creating a Python DPF object based on another Python DPF object triggered a new server instead of using the server of the object given as input.
> Fix a bug where a new server is run on object creation

- examples/12-fluids/00-fluids_model.py
- src/ansys/dpf/core/mesh_info.py
- tests/test_mesh_info.py
Add a helper for bodies in the `MeshInfo`.
> Add MeshInfo.bodies

- src/ansys/dpf/core/vtk_helper.py
- tests/test_vtk_translate.py
This PR aims at exposing helpers to convert DPF object instances to VTK object instances.
> Add vtk_helpers for DPF to VTK translation

- src/ansys/dpf/core/__init__.py
- src/ansys/dpf/core/plugins.py
This PR proposes a new module called `plugins` aimed at management of DPF Python plugins.
Here the helper `load_plugin_on_server` allows to automate the steps required to send a Python plugin server-side and load it correctly.
It is based on the idea that DPF Python plugins are shipped as Python libraries to install in the active Python virtual environment.
> Add plugins.py module with load_plugin_on_server helper

- src/ansys/dpf/core/__init__.py
- src/ansys/dpf/core/_version.py
- src/ansys/dpf/core/server_types.py
This PR implements retrieval of the package's version from its metadata, as defined in the `pyproject.toml`, as is shown in the PyAnsys best practices.
> Get package version from library metadata

- src/ansys/dpf/core/core.py
- src/ansys/dpf/core/server_context.py
- src/ansys/dpf/core/server_types.py
- tests/test_service.py
This `ServerContext` is interpreted so that the initialization is made without applying a context.
> Add a no_context ServerContext

- pyproject.toml
while with bump all necessary dependencies to versions compatible with `NumPy 2.0.0` (PyVista, MatPlotLib...)
> Limit Numpy to <2

- .github/workflows/docs.yml
- requirements/requirements_docs.txt
Also add a step in docs.yml to install `open-mesa` for `vtk`.
> Bump pyvista from 0.36.1 to 0.43.8 in /requirements

- pyproject.toml
Following an error with lower versions:
`TypeError: Channel.unary_unary() got an unexpected keyword argument '_registered_method'`
> Require grpcio>=1.63.0

- src/ansys/dpf/core/custom_operator.py
Issue with new `setuptools` behavior which creates a `__editable__.ansys_dpf_core-****.pth` instead of `ansys.dpf.core.pth` in the interpreter's `site-packages` when installing in editable mode.
Also fixed the discovery of any `original` `dpf-sites.zip`.
> Fix update_virtual_environment_for_custom_operators

- doc/source/getting_started/compatibility.rst
This PR updates the description of OS support by DPF in the documentation to mention drop of support for CentOS 7 and support starting from Rocky Linux 8.
> Update support for CentOS and Rocky 8

- .github/workflows/ci_release.yml
Bump release testing to DPF 2025.1.pre0 planned for next week.
Release CI action: https://github.com/ansys/pydpf-core/actions/runs/9987868674
> Switch release CI to DPF 2025.1.pre0

- src/ansys/dpf/core/_version.py
Add "9.1" version to be able to merge the bump to 2025.1.pre1 in the server
> Add 9.1 to prepare for post-release

- src/ansys/dpf/core/runtime_config.py
[Failing](https://github.com/ansys/pydpf-core/actions/runs/10159120565/job/28092654851#step:18:323) for Python 3.9 on Ubuntu-22.04 runner.
Removing while trying to release `ansys-dpf-core==0.13.0`.
To revert once fix is found.
> Remove problematic doctest

- README.md
- doc/source/getting_started/compatibility.rst
- doc/source/getting_started/dpf_server.rst
- doc/source/getting_started/licensing.rst
- doc/source/user_guide/how_to.rst
- examples/05-file-IO/00-hdf5_double_float_comparison.py
- examples/05-file-IO/02-hdf5_serialize_and_read.py
- examples/08-python-operators/02-python_operators_with_dependencies.py
- examples/12-fluids/03-fluids_isosurface.py
- src/ansys/dpf/core/collection_base.py
- src/ansys/dpf/core/operator_specification.py
- src/ansys/dpf/core/plugins.py
- src/ansys/dpf/core/server_context.py
- Compatibility table
- DPF Server page
> Update documentation for 2025.1.pre0

- .github/workflows/ci.yml
- .github/workflows/ci_release.yml
- .github/workflows/docs.yml
- .github/workflows/test_docker.yml
- .github/workflows/tests.yml
Also switch to artifact-upload@v4 and fix concurrent artifact upload
> Remove "if: always()" from tests.yml and bump all pydpf-actions to v2.3

- .github/workflows/ci_release.yml
This started being an [issue](https://github.com/ansys/pydpf-core/actions/runs/10654274290) for some reason.
Checked again [online](https://github.com/orgs/community/discussions/26529) and this is not officially supported for reusable workflows (not to confuse with composite actions).
Hard-coding the values instead.
This is weird as this had been working for some time.
> Fix CI release main python version envvar

- .github/ISSUE_TEMPLATE/bug.yml
Adds options:
- ANSYS 2024 R2
- DPF 2025.1.pre0
as well as:
- Python 3.13
> Add new DPF versions to the bug issue template

- src/ansys/dpf/core/dpf_operator.py
- src/ansys/dpf/core/workflow.py
- src/ansys/dpf/gate/generated/workflow_capi.py
- src/ansys/dpf/gate/operator_grpcapi.py
- src/ansys/dpf/gate/workflow_grpcapi.py
- tests/test_operator.py
- tests/test_workflow.py
Fixes #1670 
A PR is required server-side for the `LegacyGrpc` server type to work.
> Fix Any as input of operator and workflow

- .ci/update_dpf_dependencies.py
- .github/workflows/update_operators.yml
A first PR to stop updating `ansys/dpf/gate/*_grpcapi.py` files when getting code updates from new servers.
This PR means that PyDPF-Core would now have ownership of these files.
Example run of code update:
https://github.com/ansys/pydpf-core/actions/runs/10698323848/job/29657450211
> Take ownership of ansys/dpf/gate/*grpcapi.py files

- src/ansys/dpf/core/dpf_operator.py
- src/ansys/dpf/core/workflow.py
- tests/test_operator.py
- tests/test_workflow.py
The `StreamsContainer` cannot currently be instantiated or manipulated for a remote server via gRPC.
It looks like it is by design but I do not see why that would be.
This prevents from running a script working when `InProcess`, on a `gRPC` type server, if it contains any `StreamsContainer` instance.
We do for example have operators which take a `StreamsContainer` as input or provide one as output. Those can't be fed back into other operators.
> Fix connecting StreamsContainer as input or output of Operator or Workflow when InProcess

- examples/10-mesh_operations/13-nodes_in_local_coordinate_system.py
- tests/operators/test_coordinate_system.py
The modification made [here](https://github.com/ansys/pydpf-core/pull/1738/files) to follow the changes server-side were not retro-compatible with older DPF versions.
> Fix coordinate system example retro-compatibility

- .github/release.yml
Exclude `dependabot` from release notes and separate the Examples section from the Documentation section.
> Improvements to the release notes template

- doc/.vale.ini
Based on @clatapie changes in Luisa's branch.
It looks like somehow Jorge managed to push to master directly (see [here](https://github.com/ansys/pydpf-core/commit/ca11a17499f35f6a7d8f6be885a27b393aad0589)) which requires the update from Camille, otherwise it is failing as it is.
The `master` branch does have a protection rule, so I am not sure how that could happen.
> Vale upgrade TokenIgnores

- tests/test_propertyfield.py
This PR comments-out tests relative to the skin extraction operator server-side. A following PR will reactivate them and update the test references.
> Comment unit tests due to changes in skin_op

- examples/10-mesh_operations/13-nodes_in_local_coordinate_system.py
On Docker, older servers do not raise a KeyError but a DPFServerException.
See [here](https://github.com/ansys/pydpf-core/actions/runs/11314623722/job/31464828501#step:14:45) for a failing CI_release pipeline targetting `DPF 2025.1.pre0`.
> Fix Coordinate System example retro on Docker

- doc/source/conf.py
As discussed in #1749 ([33fade6](https://github.com/ansys/pydpf-core/pull/1749/commits/33fade68ec366d400711f080eceec6f563fd789d))
> adapt logo for light and dark modes

- examples/10-mesh_operations/13-nodes_in_local_coordinate_system.py
This fixes retro-compatibility of the example with DPF versions below 9.1 for the `0.13.1` release.
Passing CI for `251.pre0`: https://github.com/ansys/pydpf-core/actions/runs/11666195430
> Fix retro-compatibility for example 13-nodes_in_local_coordinate_system.py

- src/ansys/dpf/core/cyclic_support.py
- src/ansys/dpf/gate/cyclic_support_grpcapi.py
- tests/test_cyclic_support.py
Following the tests made during the pyDPF training, this PR aims to enable using the methods cs, high_low_map & low_high_map in pyDPF.
> Add CyclicSupport.cs, CyclicSupport.high_low_map & CyclicSupport.low_high_map

- .github/ISSUE_TEMPLATE/tutorial.yml
This prepares the arrival of a new section in the `User Guide` section of the documentation for `Tutorials`.
This issue template will mark the corresponding proposal as related to tutorials to differentiate them from examples.
> Add a tutorial issue template

- .github/ISSUE_TEMPLATE/examples.yml
The correct label used for examples in this repo is `examples` and not `example`.
> Fix example issue template labels

- doc/source/_static/custom.css
- doc/source/operator_reference.rst
> fix: Sphinx button border and transparency style in docs

- requirements/requirements_docs.txt
- requirements/requirements_test.txt
> Pin down vtk in requirements_test.txt

- .ci/run_examples.py
- .github/workflows/examples.yml
- examples/04-advanced/13-manage_licensing.py
The timeout was set to `1.0s`, which is sometimes too low on GitHub runners.
> Augment license check timeout in licensing example

- src/ansys/dpf/core/helpers/streamlines.py
`is not` was returning true as they are not the same string instances, while `!=` does a real comparison.
> Fix warning condition on field location for compute_streamlines

- src/ansys/dpf/core/__init__.py
- src/ansys/dpf/core/common.py
- src/ansys/dpf/core/custom_container_base.py
- src/ansys/dpf/core/dpf_operator.py
- src/ansys/dpf/core/helpers/utils.py
- src/ansys/dpf/core/outputs.py
- src/ansys/dpf/core/workflow.py
- src/ansys/dpf/core/workflow_topology/__init__.py
- src/ansys/dpf/core/workflow_topology/data_connection.py
- src/ansys/dpf/core/workflow_topology/exposed_pin.py
- src/ansys/dpf/core/workflow_topology/operator_connection.py
- src/ansys/dpf/core/workflow_topology/workflow_topology.py
- tests/conftest.py
- tests/test_any.py
- tests/test_operator.py
- tests/test_workflow.py
- tests/test_workflow_topology.py
This adds the PyDPF support of the `WorkflowData` class and `workflow_to_workflow_topology` operator,
> feat: add WorkflowTopology class and workflow_to_workflow_topology operator

- src/ansys/dpf/core/dpf_operator.py
- tests/test_operator.py
Added property `id` in class `Operator`
> feat: add Operator.id property

- src/ansys/dpf/core/misc.py
The changes in [this PR](https://github.com/ansys/pydpf-core/pull/1949) broke the Ansys finder, at least on Linux. See code comments for a description of the changes.
Tested on a Linux machine with Ansys installed at `/ansys_inc/v251` using a minimal script replicating the logic in the function `find_ansys`.
Original script:
```python
import os
from pathlib import Path
def is_float(string):
try:
float(string)
return True
except ValueError:
return False
def find_ansys():
base_path = None
if os.name == "nt":
base_path = Path(os.environ["PROGRAMFILES"]) / "ANSYS INC"
elif os.name == "posix":
for path in [Path("/usr/ansys_inc"), Path("/ansys_inc")]:
if path.is_dir():
base_path = path
else:
raise OSError(f"Unsupported OS {os.name}")
if base_path is None:
return base_path
paths = …
```
> Fix ansys installation finder

- .ci/build_doc.bat
- .github/workflows/docs.yml
- doc/source/api/index.rst
- doc/source/conf.py
- requirements/requirements_docs.txt
- src/ansys/dpf/core/misc.py
This PR is related to ansys-internal/pyansys-planning#100. The migration of the API documentation migration is being handled here.
> doc: use sphinx-autoapi for API reference

- src/ansys/dpf/core/available_result.py
This is required so that force_elemental_nodal is correctly computed for contact results in pydpf-post. As far as I can see this dictionary is only used to lookup metadata on request and does not impact the available results directly. The scripting name is taken from dataProcessingDoc.html in the dpf core repo.
> Add contact result properties

- pyproject.toml
- src/ansys/dpf/core/core.py
- src/ansys/dpf/core/fields_container.py
- src/ansys/dpf/core/help.py
- src/ansys/dpf/core/server_types.py
- tests/test_operator.py
Related to #296. flake8-todos ruff rule is enabled via this PR
> Doc: flake8 todos

- examples/09-averaging/00-compute_and_average.py
The first example of the averaging section lost its calls to plot methods at some point, not fitting the description anymore. This PR adds them back to fix the example.
> Fix averaging example plots

- src/ansys/dpf/core/dpf_operator.py
- tests/test_operator.py
Error was raised when doing:
```
from ansys.dpf.core import operators as ops
f1 = ops.utility.forward()
f2 = ops.utility.forward()
f2.inputs.any.connect(f1.outputs.any)
```
Error marked pin connection as ambiguous due to mismanagement of `Any` pin type in `Operator._find_outputs_corresponding_pins`.
The whole `Input.connect` and `Inputs.connect` needs a big refactor.
> Fix connecting Any as inpt

- .github/workflows/pydpf-post.yml
Due to hanging pipelines when tests start failing on Windows for pydpf-post, add a maxfail to the pytest call.
See for example this run https://github.com/ansys/pydpf-core/actions/runs/12711515295/job/35435017936?pr=2002
> Add maximum number of failures in PyDPF-Post test CI

- src/ansys/dpf/core/mesh_scoping_factory.py
- src/ansys/dpf/core/scoping.py
- src/ansys/dpf/core/server_types.py
- tests/test_scoping.py
Hi @JennaPaikowsky, the PR for the field inspired me to do this for the `Scoping` class as I noticed we were doing `list(range(*))` in the docstring examples for the `Field` when defining a `Scoping`.
This PR mainly adds the support for a range as input when setting the IDs of a scoping.
It also adds type hinting and improves the docstrings a bit. I'll also add some docstring examples and testing.
I'll actually add the `AnyServerType` type for type hint in a dedicated PR if @moe-ad and @jorgepiloto confirm this is the correct way to provide a combination of allowed types for type hints in the rest of the library. See #2002 
@jorgepiloto @moe-ad one thing I would like our opinion on is the type hint for pointers and Grpc messages as I think it will not work as-is. Edit: it looks like it …
> Accept a Python range when setting scoping IDs.

- src/ansys/dpf/core/mesh_scoping_factory.py
- src/ansys/dpf/core/meshed_region.py
- src/ansys/dpf/core/model.py
- tests/test_factories.py
The `server` argument of the `mesh_scoping_factory.named_selection_scoping` method had no effect.
This PR adds a deep copy of the resulting scoping to the provided server if given one.
The scoping in output is thus on the provided server.
> Fix mesh_scoping_factory.named_selection_scoping server argument

- src/ansys/dpf/core/__init__.py
- src/ansys/dpf/gate/load_api.py
The `pkg_resources` library is marked as deprecated and raises warnings.
We switch to using `importlib`.
This is done is two places:
- in the `ansys.dpf.core.__init__.py` to check the presence of `ansys-dpf-gate`, `ansys-dpf-gatebin` or `ansys-grpc-dpf` in the Python environment and raise a deprecation error.
- in `ansys.dpf.gate.load_api.__paths_to_dpf_server_library_installs` to detect installed `ansys-dpf-server***` libraries and return install paths.
> Deprecate pkg_resources usage

- src/ansys/dpf/core/_version.py
- tests/test_checkversion.py
- tests/test_version.py
Realized the current implementation of the `ServerToAnsysVersion` map would not give the right answer for `10.0` (it gives `10R0`).
Fixed this and refactored to not need to update this version map anymore for each new version.
The only requirement is for DPF to continue only bumping major for new Ansys releases.
> Fix server_to_ansys_version

- .github/workflows/ci_release.yml
- .github/workflows/tests.yml
DPF `2025.1.0` has been officially released with `ANSYS 2025 R1` and is the latest publicly available version to test against when releasing `ansys-dpf-core`.
> Bump tests to DPF 2025.1.0 in ci_release.yml

- tests/test_any.py
Failing for `2025.1.0` for `any` wheel as this is introduced with `2025.2.pre0`.
> Update test_cast_workflow_any to also skip on 2025.1.0

- src/ansys/dpf/core/dpf_operator.py
- src/ansys/dpf/core/misc.py
- src/ansys/dpf/core/workflow.py
- tests/test_operator.py
- tests/test_workflow.py
This adds support for giving lists to operator or workflow inputs in the format of a rank 1 NumPy array.
> Accept rank-1 NumPy arrays for workflow and operator inputs which accept lists 

- src/ansys/dpf/core/inputs.py
- tests/test_operator.py
The current `Inputs.connect` method tries to connect an object to an input pin accepting the object type.
This worked when only one input accepted a certain type, and raised an error about ambiguity when several were available.
This effectively prevents from having operators with two inputs accepting a same type.
This PR changes the current behavior in two ways:
- it allows for operators with two inputs accepting a same type to use this method to ensure retro-compatibility of scripts, and it picks the first input found accepting the type, **raising a warning instead of an errror**.
- it marks the `Inputs.connect` method as deprecated in favor of explicit output-to-input connections.
> Deprecate Inputs.connect and handle ambiguous connections

- requirements/requirements_build.txt
Reverts ansys/pydpf-core#2052
`black` is currently used when generating the python code for operators [here](https://github.com/ansys/pydpf-core/blob/f3d5f989e8763f70c389457ed304d623eec9ac1a/src/ansys/dpf/core/operators/build.py#L168).
> Revert "fix: remove black as a dependency"

- .github/workflows/update_operators.yml
While running test operator update actions, the `integration_proxies` keep being added as reviewer despite the generated PR being on a feature branch.
This limits it to operator update PRs on the default branch.
See [here](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#example) for example of `if/else` in GitHub actions expressions.
> Only ask integration_proxies for review for operator updates on main branch

- pyproject.toml
Removing unused dependency brought during merge of `ansys-dpf-core` with `ansys-grpc-dpf` and `ansys-dpf-gate`.
Thanks @koubaa for the catch
> Maint: Remove google-api-python-client from dependencies 

- src/ansys/dpf/core/inputs.py
- tests/operators/test_change_shell_layers.py
Solves #210 
Operators do not take `Enum` as input, so `Enum` types must be translated to their `int` value.
This issue was found for the `shell_layers` Enum when trying to connect it to the `change_shell_layers` operator.
> Handle connection of Enum to operators

- src/ansys/dpf/core/operator_specification.py
- tests/test_operator.py
This used to throw an "invalid type" CLayer error for an empty `Specification` when `InProcess`. Now it returns an empty `ConfigSpecification`.
> Fix specification.config_specification on empty spec

- src/ansys/dpf/core/workflow.py
- tests/test_workflow.py
Solves #928 
PR on PyDPF-Post will make use of new `Workflow.safe_connect_with()`.
Edit: not sure about the naming. Should it rather be `Workflow.connect_with_available`, or something else? @BClappe 
Also I realize that changing the behavior of `Workflow.connect_with` to now raise if an input or output is unavailable, is a breaking change of a sort. Maybe we should actually keep `connect_with` as-is or even put the filtering logic there, and create a new method `Workflow.connect_with_error` which raises in the case of an unavailable input or output. What do you think?
> Raise useful error on workflow.connect_with for wrong labels

- .ci/code_generation.py
- src/ansys/dpf/core/dpf_operator.py
- src/ansys/dpf/core/inputs.py
- src/ansys/dpf/core/operator_specification.py
- src/ansys/dpf/core/operators/build.py
- src/ansys/dpf/core/operators/math/accumulate.py
- src/ansys/dpf/core/operators/math/accumulate_fc.py
- src/ansys/dpf/core/operators/math/add_constant.py
- src/ansys/dpf/core/operators/math/add_constant_fc.py
- src/ansys/dpf/core/operators/math/correlation.py
- src/ansys/dpf/core/operators/math/mac.py
- src/ansys/dpf/core/operators/math/scale.py
- src/ansys/dpf/core/operators/math/scale_fc.py
- src/ansys/dpf/core/operators/operator.mustache
- src/ansys/dpf/core/outputs.py
- src/ansys/dpf/gate/operator_specification_grpcapi.py
- tests/test_animation.py
- tests/test_animator.py
- tests/test_specification.py
This PR exposes APIs for pin name aliases in PyDPF-Core, along with a template update for operator module generation to enable retro-compatibility of scripts using aliases, as well as warning about deprecation of said aliases.
> Pin aliases

- src/ansys/dpf/core/collection_base.py
- src/ansys/dpf/core/custom_type_field.py
- src/ansys/dpf/core/field.py
- src/ansys/dpf/core/property_field.py
- src/ansys/dpf/core/scoping.py
- src/ansys/dpf/core/string_field.py
- src/ansys/dpf/gate/dpf_vector.py
When working on distributed workflows (in process and gRPC), DPFVector were sometimes created on one clayer and deleted on another. This prevented any changes in the DPFVector.
> DpfVector BUG: DpfVector were created on one clayer and deleted in another 

- .github/workflows/test_docker.yml
- .github/workflows/tests.yml
- tox.ini
This PR adds test result upload to Codecov to start getting test analytics (test failure rates and average duration over commits for dev branches and over time for the main branch).
This will ease identification of flaky tests and prioritization of investigations for random failures.
> Ci: add test analytics

- tests/test_geometry.py
Removing tests in test_geometry.py on create_plane_from_lines as this helper is wrong anyway and this is blocking pyvista updates where a check has been added.
Hesitating with pure deprecation of the helper as defining a plane from two lines (four points) is undefined behavior anyway.
> Comment failing tests for geometry helper

- .github/workflows/ci.yml
- .github/workflows/pydpf-post.yml
The PyDPF-Core CI runs PyDPF-Post tests for information purposes thanks to its `pydpf-post.yml` workflow.
This PR makes sure that the workflow is always reported as successful to not stop people from merging, while still [reporting errors](https://github.com/marketplace/actions/continue-on-error-comment) for PyDPF-Post tests as comments in the PR if any.
This is most useful for `server-sync` PRs.
> ci: make pydpf-post job information-only

- src/ansys/dpf/core/elements.py
- tests/test_elements.py
Properly support the number of nodes, number of corner nodes and nmber of quadratic nodes in the Beam3 ElementDescriptor
> Support Beam3 in ElementDescriptor

- pyproject.toml
Fixes #2308 
For some reason `imageio` was still limited to `2.28.0` in `pyproject.toml` despite requirement files testing for the latest.
This resulted in the bug linked above.
> fix(dependencies): Remove upper limit on imageio in pyproject.toml

- .github/workflows/ci.yml
This makes use of `ansys/actions/doc-deploy-pr@v10` to deploy the doc built by the PR for easy review
> ci(doc): upload PR doc

- .github/workflows/ci.yml
Adds back 25R2 to retro testing following its removal by https://github.com/ansys/pydpf-core/pull/2292
> ci: test 25R2 retro-compatibility

- src/ansys/dpf/core/custom_type_field.py
- src/ansys/dpf/gate/dpf_vector.py
- tests/test_custom_type_field.py
- tests/test_dpf_vector.py
Solves #2405 by raising an error at creation of a custom type entity (`CustomTypeField` or `DPFVectorCustomType`) if the type is not convertible to a `ctype`.
> fix: custom type check for unsupported type

- src/ansys/dpf/core/fields_container.py
- src/ansys/dpf/core/plotter.py
> feat(plotter): return the plotter instance

- tests/operators/test_change_shell_layers.py
… for Ubuntu with DPF 24R2 and older (failure under investigation)
#2424
> ci(test): skip test-operators/test_operator_change_shell_layers_connect_enum

- src/ansys/dpf/core/common.py
Location `Modal` is already exposed via operators for modal expansion, it is however lacking in PyDPF.
> feat: expose modal location

- examples/06-plotting/00-basic_plotting.py
Due to #511 and a bug preventing from plotting ElementalNodal results on shells for DPF 25R1 and below.
> fix(example): fix retro with 25R1 and below for 00-basic_plotting.py

- doc/source/user_guide/tutorials/custom_operators_and_plugins/custom_operators.rst
- doc/source/user_guide/tutorials/custom_operators_and_plugins/index.rst
- src/ansys/dpf/core/examples/python_plugins/custom_operator_example.py
Fixes retro of the tutorial with 252 and below.
https://github.com/ansys/pydpf-core/actions/runs/16499565827/job/46654081741#step:8:46
> tuto(custom): custom operators tutorial supports older DPF versions

- doc/source/user_guide/tutorials/custom_operators_and_plugins/index.rst
This PR corrects how the card of the "Custom operators" tutorial  renders on the "Custom Operators and Plugins" tutorial section
Before: 
After:
> doc(tutorials): Correct card of the "Custom operators" tutorial

- .github/workflows/ci.yml
- .github/workflows/ci_release.yml
This PR makes the retro job in ci.yml run for versions in repository variables ANSYS_VERSIONS_RETRO and ANSYS_VERSION_LAST_RELEASED, as well as makes the retro job in ci_release.yml run for versions in repository variable ANSYS_VERSIONS_RETRO.
> ci: use repository variables for retro testing matrices

- src/ansys/dpf/core/any.py
- src/ansys/dpf/gate/any_grpcapi.py
- tests/test_any.py
Solves #2486 by adding explicit support for cast from `Any` to `DataSources`
> fix(any): fix cast of Any to DataSources

- .github/workflows/ci.yml
- .github/workflows/doc-deploy-pr.yml
Moves the `doc-deploy-pr` action to a dedicated workflow triggered by a `workflow_run` `completed` on `docs.yml`, and deploying only if the PR is labeled with `deploy-pr-doc`.
The new workflow needs to be present in the main branch to be triggered.
> ci(doc): Switch doc-deploy-pr to a dedicated workflow

- examples/07-distributed-post/03-distributed-msup_expansion_steps.py
In my last PR of correction, I missed transforming one of the operators "displacement" to "modal_coordinate".
> Convert "displacement" to "modal_coordinate" - Part 2

- src/ansys/dpf/core/documentation/toc_template.j2
Requires https://github.com/ansys/DevRelDocs/pull/230
> doc(dpf): A the "build local documentation" section to the toc_template.j2 for DPF doc generation
