ansys/pydpf-core

.ci/azure-pipelines.yml, ansys/dpf/core/examples/downloads.py, examples/03-advanced/04-extrapolation_stress_3d.py, examples/03-advanced/05-extrapolation_strain_2d.py
=> dpf_extrapolate_examples

ansys/dpf/core/data_sources.py, ansys/dpf/core/dimensionality.py, ansys/dpf/core/dpf_operator.py, ansys/dpf/core/element_descriptor.py, ansys/dpf/core/elements.py, ansys/dpf/core/errors.py, ansys/dpf/core/field.py, ansys/dpf/core/field_base.py
This really doesn't get easier! I'm being exposed to lots of new stuff here.
=> Doc/edits to py files from d to field_base.py

tests/conftest.py, tests/test_checkversion.py, tests/test_code_docstrings.py, tests/test_codegeneration.py, tests/test_cyclic_support.py, tests/test_datasources.py, tests/test_elements.py, tests/test_examples.py, tests/test_factories.py, tests/test_field.py, tests/test_fieldscontainer.py, tests/test_hdf5.py, tests/test_launcher.py, tests/test_meshescontainer.py, tests/test_meshregion.py, tests/test_model.py, tests/test_multi_server.py, tests/test_operator.py, tests/test_operatorshelper.py, tests/test_plotter.py, tests/test_plugins.py, tests/test_propertyfield.py, tests/test_resultinfo.py, tests/test_scoping.py, tests/test_scopingscontainer.py, tests/test_service.py, tests/test_timefreqsupport.py, tests/test_workflow.py
Format files under tests directory with black.
=> Format test files

README.md
=> Mention link to doc in readme

.ci/azure-pipelines.yml, .ci/templates/prepare-environment-linux.yml, examples/00-basic/06-load_plugin.py, examples/04-specific-requests/00-hdf5_double_float_comparison.py
Move documentation build to Linux and remove Windows documentation build to address the legends issue in the example images. The doc package produced from the linux build has the legends showing properly:
=> Add linux doc build

ansys/dpf/core/plotter.py
=> Plotter: return_cpos (kwargs) updates with a field display

examples/05-plotting/00-plot_on_path.py
Update 00-plot_on_path.py example script.
=> Examples: 05-plotting updated

ansys/dpf/core/server.py, tests/conftest.py, tests/test_multi_server.py
remove delay for python process exit
=> Server shutdown improvement

docs/source/user_guide/index.rst, docs/source/user_guide/xmlfiles.rst
The content has been reviewed and approved for the C++ API already, it just needs a formatting check.
=> Added DPF XML File content

docs/source/contributing.rst
=> Fix wrong support email in Contributing

.github/workflows/ci.yml
Removes a previously necessary step of installing a local gatebin package fro Linux standalone.
=> Remove gatebin installation step for Linux

.github/workflows/docs-style.yml, docs/.vale.ini, docs/styles/.gitignore, docs/styles/Vocab/ANSYS/accept.txt
=> Implement vale

examples/00-basic/12-get_material_properties.py
implemented review suggestions
=> implemented review suggestions

.github/workflows/ci.yml
Add the mandatory retro-compatibility tests to every PR.
=> Run retro tests on every PR

.github/workflows/ci.yml, docs/source/conf.py, examples/06-distributed-post/README.txt
Solves https://github.com/pyansys/pydpf-core/issues/428
The Documentation check passes but the documentation artifact is actually empty (easily verified with its small size of 48 kB, should be more than 100MB).
The last known Documentation generation job to work was [here](https://github.com/pyansys/pydpf-core/actions/runs/2901998839) on August 22.
Was rerun to check for unseen change in a dependency, it still passed.
Seems to have started with bump of Graphviz to 0.20.1 [here](https://github.com/pyansys/pydpf-core/actions/runs/2754279313). Cannot find an occurrence before that.
Two problems here:
the documentation check did not see something was wrong with the doc (artifact too small / step too short)
no error was raised although something went obviously wrong
EDIT: was due do the vtk …
=> Fix the documentation generation

ansys/dpf/core/_version.py
Bump the master dev version following the release of 0.6.0
=> Bump to 0.6.1dev0

README.md
Resolves #501. Image update to show support for Python 3.7 - 3.10.
=> Update python badge image

.github/ISSUE_TEMPLATE/bug.yml
Modify link according to comment in pyansys/pydpf-post#167.
=> modify link in bug template

ansys/dpf/core/_version.py
=> Bump to 0.6.2.dev0

ansys/dpf/core/model.py
Improves performance when reading a mesh with numerous named selections.
=> Improve performance Metadata.mesh_provider

docs/source/getting_started/compatibility.rst
- Update the compatibility table
=> Update the compatibility documentation

tests/conftest.py, tests/test_python_plugins.py
Add fixture with ``testfiles`` dir and use it to fix local path to pythonPlugins.
=> Fix testfiles path

docs/source/getting_started/install.rst
=> Fix links for wheels

examples/00-basic/12-get_material_properties.py
=> Improve `get_material_properties` example

README.md
Resolves #772, which asks for an update of the Readme.md to mention the DPF Server.
=> Mention DPF Server in the Readme.md

.github/workflows/ci.yml, .github/workflows/releaser.yml
Fix #813 by updating `doc-deploy-dev` and `doc-deploy-stable.`
=> CI: update doc-deploy versions

src/ansys/dpf/core/operators/mesh/meshes_provider.py
due to an error server-side it has been overridden by acmo:meshes_provider
=> Revert last changes to operators.mesh.meshes_provider

.github/workflows/ci.yml, .github/workflows/releaser.yml, docs/source/conf.py, requirements/requirements_docs.txt
Enables stable multi-version documentation
=> Bump to pyansys/doc_deploy@v4

docs/source/user_guide/getting_started_with_dpf_server.rst
Added "avrxp_snd_level1" as DPF increment in doc in preparation for this PR on TFS:
https://tfs.ansys.com:8443/tfs/ANSYS_Development/DPF/_git/DPF/pullrequest/376628
=> update increments list

tests/test_server.py
Removed unnecessary calls to shutdown_all_session_serves
=> Fixed start_shutdown test

README.md
Due to multi-versioning, the links to the doc were broken
=> Update links to doc in Readme

examples/01-transient_analyses/02-lsdyna_operators.py
=> Mark lsdyna_operators example as requiring DPF 6.1

README.md, docs/source/contributing.rst
Change the support email address, explain how to change doc versions, and clean up the README file.
=> Change email address and explain how to change doc versions

.github/workflows/ci_release.yml
https://github.com/pyansys/pydpf-core/actions/runs/4948793861/jobs/8850028117#step:5:5710
=> Fix ci_release.yml/docker_examples call

src/ansys/dpf/core/inputs.py, src/ansys/dpf/core/mapping_types.py
#933 
Edit: does not solve #933 as "solving" it raises a lot of errors in dosctrings and tests due to what is behind the faulty conditional being erroneous. Dropping this unrelated change from this PR.
=> Label space operator input accept Python dict

.github/workflows/ci_release.yml
=> Switch ci_release.yml to 241.1.pre0

docs/source/index.rst
=> Reorder documentation sections

.github/workflows/releaser.yml
to define which branch/tag reference the Meili step checks out
=> Add a checkout_ref optional argument to releaser.yml

tests/test_resultinfo.py
Change one test to merge TFS side CFX zones refactoring (test_print_available_result_with_qualifiers)
=> Comment tests after changes in CFF

docs/source/getting_started/index.rst
=> Fix Vale warning

src/ansys/dpf/core/server.py
=> Always connect to a server via LegacyGrpc when on macOS

.github/workflows/docs.yml
Set the MEILISEARCH_PUBLIC_API_KEY environment variable in docs.yml
=> Fix dev doc search engine

examples/12-fluids/00-fluids_model.py, src/ansys/dpf/core/mesh_info.py, tests/test_mesh_info.py
Add MeshInfo.zones, MeshInfo.cell_zones and MeshInfo.face_zones to get dictionaries mapping IDs to zone names.
=> Add Meshinfo zone helpers

requirements/requirements_docs.txt, src/ansys/dpf/core/server_factory.py
Bump to `ansys_sphinx_theme==0.13.0`
And fox a dosctring error.
=> Fix doc generation

doc/source/conf.py
https://github.com/ansys/pydpf-core/actions/runs/7568336117/job/20609347324?pr=1358#step:18:18
=> Skip unstable distributed_stress_averaging example in doc generation

.github/workflows/ansys_lab.yml, .github/workflows/update_operators.yml
Example of working workflow:
https://github.com/ansys/pydpf-core/actions/runs/7568342361/job/20609355155
=> Switch to pyansys ci bot

src/ansys/dpf/core/__init__.py, src/ansys/dpf/core/generic_data_container.py, tests/test_generic_data_container.py
Fix GenericDataContainer APIs to be able to set/get properties of types bytes and Collection
=> GDC set bytes and collection

doc/source/getting_started/licensing.rst
=> Fix Sound license increment name

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/examples.yml, .github/workflows/examples_docker.yml, .github/workflows/pydpf-post.yml, .github/workflows/test_docker.yml, .github/workflows/tests.yml, .github/workflows/update_operators.yml
Upgrading the CI to target 251 DPF by default
=> Update CI for 251

.github/workflows/ci.yml, .github/workflows/ci_release.yml, .pre-commit-config.yaml
This pull-request implements the usage of [ansys/actions/code-style action](https://actions.docs.ansys.com/version/stable/style-actions/index.html#code-style-action) in the CI/CD pipelines of the project.
=> ci: use ansys/actions/code-style

src/ansys/dpf/core/results.py
=> comment the docstring that is failing du to new element types (INTER and MPC)

src/ansys/dpf/core/any.py, src/ansys/dpf/core/common.py, src/ansys/dpf/core/generic_data_container.py, src/ansys/dpf/core/property_field.py
- Remove 2 dict copies in Any cast
- Cache GDC properties descriptions
- Load field definition on demand
=> Improve performance of GenericDataContainer get_property

requirements/requirements_docs.txt
It is not an actual requirement
=> Remove sphinx-autobuild as doc requirement

.github/workflows/ci.yml, .github/workflows/releaser.yml
This pull-request fixes the issues raised in https://github.com/ansys/ansys-sphinx-theme/actions/runs/11459431277 by including bot user and email in the deploy actions.
=> fix: missing bot secrets in deploy actions

src/ansys/dpf/core/_version.py
Add 25.2 handling in version to switch to DPF 2025R2.
=> build: add 25.2 handling in version

.github/workflows/ci.yml
Switch to 25.2 server dev branch following ECC for 25.1
=> Target 25.2 in ci.yml

doc/source/conf.py
=> Fix PyAnsys logo link in doc

pyproject.toml
Following release of `0.13.3`.
=> Bump 0.13.4.dev0

doc/source/links_and_refs.rst
Add a file with substitution text to be used around the doc for the main DPF objects and useful links
=> Add a links and refs file to be used in the doc 

doc/source/operator_reference.rst
=> Fixed text issue

src/ansys/dpf/core/dpf_operator.py, src/ansys/dpf/core/meshed_region.py, src/ansys/dpf/core/session.py, src/ansys/dpf/core/workflow.py, tests/test_cache.py
The current client does not support DPF<4.0 so any code related to that is irrelevant.
=> Remove code specific to unsupported old DPF servers

src/ansys/dpf/core/available_result.py
Add a couple of new homogeneities to the client
=> Add new homogeneities

.github/workflows/test_docker.yml, .github/workflows/tests.yml, requirements/requirements_test.txt, src/ansys/dpf/core/workflow.py, tests/test_workflow.py
Now covered in the test pipelines despite `CodeCov` reporting otherwise.
=> Fix Workflow.view and add graphviz to the testing environment

examples/04-advanced/00-multistage_advanced_options.py, examples/11-cyclic-symmetry/01-modal_cyclic.py, examples/11-cyclic-symmetry/02-modal_cyclic_no_expansion.py
Modify old calls to cyclic_expanded_result to result in examples. 
Associated pipelines with TFS code: 
https://github.com/ansys/pydpf-core/actions/runs/13856464751/job/38778362266?pr=2159
=> Cyclic examples modifications to set up cyclic operators private

examples/00-basic/02-basic_field_containers.py
https://tfs.ansys.com:8443/tfs/ANSYS_Development/Portfolio/_workitems/edit/1174237/
=> Fixed typo

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/examples.yml, .github/workflows/examples_docker.yml, .github/workflows/pydpf-post.yml, .github/workflows/test_docker.yml, .github/workflows/tests.yml, .github/workflows/update_operators.yml
The current DPF version under development is now 26R1
=> Move CI to 26R1

doc/source/getting_started/contribute/developer.rst, doc/source/user_guide/tutorials/custom_operators_and_plugins/update_pydpf_core.rst
Based on @gogo2464's findings. Much appreciated!
=> chore: use --index-url instead of --extra-index-url
